language: generic
services:
  - docker

before_install:
  - docker build -t skoffie/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true skoffie/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-490593598170"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

