language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t skoffie/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true skoffie/docker-react npm run test